#!/usr/bin/env python3
# -*- coding:utf-8 -*-


def remove_special_charx(s):
    s = s.replace("</i>", "")
    s = s.replace(u'Á', "A")
    s = s.replace(u'á', "a")
    s = s.replace(u'à', "a")
    s = s.replace(u'ä', "a")
    s = s.replace(u'â', "a")
    s = s.replace(u'?', "a")
    s = s.replace(u'ã', "a")
    s = s.replace(u'å', "aa")
    s = s.replace(u'Ç', "C")
    s = s.replace(u'ç', "c")
    s = s.replace(u'ð', "d")
    s = s.replace(u'É', "E")
    s = s.replace(u'È', "E")
    s = s.replace(u'é', "e")
    s = s.replace(u'ë', "e")
    s = s.replace(u'è', "e")
    s = s.replace(u'ê', "e")
    s = s.replace(u'Í', "I")
    s = s.replace(u'í', "i")
    s = s.replace(u'ï', "i")
    s = s.replace(u'Ñ', "N")
    s = s.replace(u'ñ', "n")
    s = s.replace(u'Ó', "O")
    s = s.replace(u'Ö', "O")
    s = s.replace(u'Ø', "O")
    s = s.replace(u'ö', "o")
    s = s.replace(u'ó', "o")
    s = s.replace(u'ò', "o")
    s = s.replace(u'ô', "o")
    s = s.replace(u'ø', "o")
    s = s.replace(u'Š', "S")
    s = s.replace(u'š', "s")
    s = s.replace(u'Ü', "U")
    s = s.replace(u'ú', "u")
    s = s.replace(u'ü', "u")
    s = s.replace(u'ý', "y")
    s = s.replace(u'Ž', "Z")
    s = s.replace(u'ž', "z")
    s = s.replace(u'ß', "ss")
    s = s.replace(u'æ', "ae")
    s = s.replace(u'’', "'")
    s = s.replace(u'&nbsp;', " ")
    s = s.replace(u'&amp;', "&")
    s = s.replace(u'&#259;', "a")
    s = s.replace(u'&#261;', "a")
    s = s.replace(u'&#262;', "C")
    s = s.replace(u'&#268;', "C")
    s = s.replace(u'&#269;', "c")
    s = s.replace(u'&#263;', "c")
    s = s.replace(u'&#281;', "e")
    s = s.replace(u'&#283;', "e")
    s = s.replace(u'&#287;', "g")
    s = s.replace(u'&#304;', "I")
    s = s.replace(u'&#305;', "i")
    s = s.replace(u'&#317;', "L")
    s = s.replace(u'&#321;', "L")
    s = s.replace(u'&#322;', "l")
    s = s.replace(u'&#324;', "n")
    s = s.replace(u'&#326;', "n")
    s = s.replace(u'&#328;', "n")
    s = s.replace(u'&#337;', "o")
    s = s.replace(u'&#345;', "r")
    s = s.replace(u'&#350;', "S")
    s = s.replace(u'&#351;', "s")
    s = s.replace(u'&#355;', "t")
    s = s.replace(u'&#367;', "u")
    s = s.replace(u'&#537;', "s")
    s = s.replace(u'\xad', "")
    s = s.replace(u'\u0107', "c")
    s = s.strip()
    return s

def remove_special_char(s):
    # special
    s = s.replace('&#263;', 'c')
    # aA
    s = s.replace('á', 'a')
    s = s.replace('ã', 'a')
    s = s.replace('ä', 'a')
    s = s.replace('à', 'a')
    s = s.replace('å', "aa")
    s = s.replace('ą', 'a')
    s = s.replace('â', 'a')
    s = s.replace('ă', 'a')
    s = s.replace('æ', 'ae')
    s = s.replace('Á', 'A')
    # oO
    s = s.replace('ö', 'o')
    s = s.replace('ó', 'o')
    s = s.replace('Ö', 'O')
    s = s.replace('ø', 'o')
    s = s.replace('Ó', 'O')
    s = s.replace('ô', 'o')
    s = s.replace('ð', 'o')
    s = s.replace('ō', 'o')
    s = s.replace('ò', 'o')
    s = s.replace('Ø', 'O')
    # eE
    s = s.replace('ë', 'e')
    s = s.replace('é', 'e')
    s = s.replace('è', 'e')
    s = s.replace('ę', 'e')
    s = s.replace('ě', 'e')
    s = s.replace('ê', 'e')
    s = s.replace('È', 'E')
    s = s.replace('É', 'E')
    # i
    s = s.replace('í', 'i')
    s = s.replace('ï', 'i')
    s = s.replace('ı', 'i')
    s = s.replace('İ', 'I')
    s = s.replace('Í', 'I')
    # uU
    s = s.replace('ü', 'u')
    s = s.replace('ú', 'u')
    s = s.replace('ů', 'u')
    s = s.replace('Ü', 'U')
    # consonants
    s = s.replace('Ď', 'D')
    s = s.replace('ñ', 'n')
    s = s.replace('ń', 'n')
    s = s.replace('Ñ', 'N')
    s = s.replace('ß', 'ss')
    s = s.replace('š', 's')
    s = s.replace('ş', 's')
    s = s.replace('ș', 's')
    s = s.replace('Š', 'S')
    s = s.replace('Ś', 'S')
    s = s.replace('ç', 'c')
    s = s.replace('č', 'c')
    s = s.replace('ć', 'c')
    s = s.replace('Ç', 'C')
    s = s.replace('Ć', 'C')
    s = s.replace('Č', 'C')
    s = s.replace('ý', 'y')
    s = s.replace('ž', 'z')
    s = s.replace('ź', 'z')
    s = s.replace('Ż', 'Z')
    s = s.replace('Ž', 'Z')
    s = s.replace('ğ', 'g')
    s = s.replace('Ł', 'L')
    s = s.replace('Ľ', 'L')
    s = s.replace('ł', 'l')
    s = s.replace('ř', 'r')
    s = s.replace('ţ', 't')
    s = s.strip()
    return s